### ISSUE TITLE
printf for 64 Bit types

### ISSUE THREAD

**Issue by tk-ka** [agra-uni-bremen/riscv-vp#15]
**printf()** does not work correctly for 64 Bit integers. This might be related to #14 .

Test-code:
```
unsigned long int x = 0x123456789ABCDEF0;  
printf("64-Bit variable as decimal: %d \t %ld \t %lld \n", x, x, x);
printf("64-Bit variable as unsigned: %u \t %lu \t %llu \n", x, x, x);
``` 

Expected output:
```
64-Bit variable as decimal: -1698898192 	 1311768467463790320 	 1311768467463790320  
64-Bit variable as unsigned: 2596069104 	 1311768467463790320 	 1311768467463790320 
```

Observed output (code just added to main.c of printf test-software):
```
64-Bit Variable as decimal: -1698898192 	 -1698898192 	 6891036400 
64-Bit Variable as unsigned: 2596069104 	 2596069104	 6891036400
```

**Comment by CA92697** [comment]
That's a very interesting observation, that triggered an idea! I agree, it's indeed related to #14 so I will post it there.
Just note that #14 is observed on my 32-bit architecture. Yours appears to be 64-bit since your 'long' is already 64 bits.

**Comment by Cirromulus** [comment]
see #14
