### ISSUE TITLE
LUA 5.3 Linking : undefined reference to symbol 'dlclose@@GLIBC_2.2.5

### ISSUE THREAD

**Issue by disdi** [agra-uni-bremen/riscv-vp#25]
In building hifive env, below error is seen during linking : 

 `usr/local/lib/liblua.a(loadlib.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5`

**Comment by Cirromulus** [comment]
Thanks for looking into it!
We don't want any hardcoded library paths in there, so we can't accept this patch.
But you can add the path to the cmake command if your system has different versions of the glibc:
`cmake -DLUA_LIB="/path/to/lua;/others" ..`
