### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by ROOCKIET** [agra-uni-bremen/riscv-vp#4]
In README.md ,step 2) iii) ,after $ make install, the process is interrupted，i got error message 
'root@.../riscv-vp/vp/build# make install
[  7%] Built target core-common
[ 12%] Built target rv32
[ 17%] Built target rv64
[ 28%] Built target gdb
[ 37%] Built target gdb-mc
[ 50%] Built target platform-common
[ 55%] Built target platform-basic
[ 58%] Built target riscv-vp
[ 75%] Built target hifive-vp
[ 78%] Built target tiny32-vp
[ 82%] Built target tiny32-mc
[ 85%] Built target tiny64-vp
[ 89%] Built target tiny64-mc
[ 92%] Built target test32-vp
[ 96%] Built target linux-vp
[100%] Built target linux32-vp
Install the project...
-- Install configuration: "Debug"
CMake Error at src/platform/basic/cmake_install.cmake:42 (file):
  file INSTALL cannot find "/home/.../riscv-vp/vp/build/bin/riscv-vp".
Call Stack (most recent call first):
  src/platform/cmake_install.cmake:38 (include)
  src/cmake_install.cmake:38 (include)
  cmake_install.cmake:37 (include)
  

Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1
'
but if use $ make riscv-vp ,i could get the 'riscv-vp' in build/bin.

**Comment by Cirromulus** [comment]
I cant reproduce this behavior.
Which version of CMake are you using?

**Comment by ROOCKIET** [comment]
> I cant reproduce this behavior.
> Which version of CMake are you using?

cmake  version 3.5.1
And I found use $ make install/local,there is no error and i could get the related vps including ‘riscv-vp'’ in build/bin.
